### ISSUE TITLE
entity 패키지 구현

### ISSUE THREAD

**Issue by Kimhanju0210** [Team-MindWay/Dormitory-Manager-BackEnd#1]
## Entity 패키지 구현

entity 패키지를 구현한 후 User 클래스를 만들기

### User 클래스 내용

- `private long id;`
- `private String name;`
- `private int penalty_point;`
- `private String to_day_clean;`
- `private int clean_point;`
- `private int rank;`

**Comment by yusung103** [comment]
User 클래스는 임의로 만들어놨으니 수정할 부분은 수정하셔도 됩니다!
